### ISSUE TITLE
Host and Run Safe Places

### ISSUE THREAD

**Issue by KLouisy** [tripleblindmarket/safe-places#24]
I think it would be best to have a running version of this tool, that public health and government officials can play with. Not sure where we would host it, but we can upload our own geodata and use this as a "live" version. 

- Khahlil

**Comment by tushar-dadlani** [comment]
we can just use netlfiy for this, it's a free tool.

**Comment by ecausarano** [comment]
> we can just use netlfiy for this, it's a free tool. 

Free but only for small personal projects. I’d say we should pick a provider and ask them for free credits

**Comment by E3V3A** [comment]
* https://app.netlify.com/signup

**Comment by penrods** [comment]
The issue is the Google Maps API key, I don't think Netlify solves that does it?  Getting map data requires a billable account, which is what the API key gets you.

**Comment by Ferrumofomega** [comment]
I just signed up for Google's dev account and have a whole $300 bonus! I'm OK to stand one up and then keep an eye in event it gets close to over. That work @penrods?

**Comment by E3V3A** [comment]
> 
> 
> The issue is the Google Maps API key, I don't think Netlify solves that does it? Getting map data requires a billable account, which is what the API key gets you.

No, it need two things:

* API key  **AND**
* and active Billable account. (Expired CC's won't do.)

**Comment by mundanelunacy** [comment]
Been talking to Sam and Yasaman on joining the team.  I have a working prototype of something nearly identical to your SafePaths tool that you can see here:   https://covidmaps.org

Before you guys get this in front of healthcare officials would love to chat about potentially merging these projects https://github.com/mundanelunacy/covidmaps

**Comment by E3V3A** [comment]
@mundanelunacy 
Look cool! :+1:  Check my issue in your repo.

**Comment by kylemtowle** [comment]
Why doesn't the githack version of this work for HA's to play with their data? I've uploaded mine and played with it via githack and works terrifc.

**Comment by penrods** [comment]
I think this is dealt with now.  To implement, either get an API key (for experimentation) or implement the API for a production system.
