### ISSUE TITLE
How to setup and run this?

### ISSUE THREAD

**Issue by E3V3A** [tripleblindmarket/safe-places#29]
I'd like to try this as part of private-kit. How can I set this up to run?

**Comment by penrods** [comment]
As shown in the README, you can run directly from Github:
https://raw.githack.com/tripleblindmarket/safe-places/master/location-scrubber/index.html

You do need a Google Maps Javascript API key.  I believe you can get those freely from Google.

**Comment by penrods** [comment]
I'll add a link to the Publisher, also.

**Comment by E3V3A** [comment]
I tried to use it, but it doesn't work at all in Firefox... 
Says there's a map error and the only clocking that works is selecting a rectangle, the other buttons do nothing...

**Comment by penrods** [comment]
I use it in Chrome/Chromium, let me know if you can try that with success.

**Comment by E3V3A** [comment]
In FF:
* the drawing tools are covered by the redaction tool window. 
* there's an error (from google) about page not being able to load correctly. 
* Even after i manage to draw points and boxes, the save button is always grayed out.
* annoyingly the map **always** start in Boston. I'm not in Boston, so where do I change this default? 

![firefox_2020-04-12_23-06-32](https://user-images.githubusercontent.com/194392/79078843-e64edc80-7d13-11ea-8644-890864bf4912.png)
![firefox_2020-04-12_23-14-17](https://user-images.githubusercontent.com/194392/79078848-e949cd00-7d13-11ea-8f89-d149d300ef96.png)



In Brave (a Chrome mod) there's only a blank page...

---

PS. I tried to load some location data exported from Google, but it complains that the format is wrong. So I have no idea what is expected here... 

Please update your readme so we can get started more quickly.

**Comment by penrods** [comment]
I believe this is convered adequately now.
