### ISSUE TITLE
The drawing tools are covered by the redaction tool window.

### ISSUE THREAD

**Issue by E3V3A** [tripleblindmarket/safe-places#41]
The drawing tools are covered by the redaction tool window.

**Comment by penrods** [comment]
What drawing tools do you mean?  Redaction is not supposed to allow drawing, just select and delete.

**Comment by E3V3A** [comment]
This one: 


![firefox_2020-04-12_23-06-32](https://user-images.githubusercontent.com/194392/79078843-e64edc80-7d13-11ea-8644-890864bf4912.png)

**Comment by penrods** [comment]
Those default Google tools are intentionally covered, all tools are in the control panel.
