### ISSUE TITLE
Add clear instructions how to correctly get API key and activate Billing

### ISSUE THREAD

**Issue by E3V3A** [tripleblindmarket/safe-places#44]
Add clear instructions to the readme on how to:
- [ ] 1. Get an Google API key (for the map) starting from having only a gmail account. (How to navigate and what to click etc.)
- [ ] 2. How to enable account Billing in the Google  console

**Comment by penrods** [comment]
The default now links to https://developers.google.com/maps/documentation/javascript/get-api-key which provides very clear step-by-step instructions.
