### ISSUE TITLE
How to import external JSON file in the Publisher app?

### ISSUE THREAD

**Issue by E3V3A** [tripleblindmarket/safe-places#45]
I'm not able to import anything into the publisher app. Always get some error about the JSON. 

What is the correct format and how to import it?

**Comment by penrods** [comment]
Format is the same as what is exported from Safe Paths.  Eg:

```json
[
   {"latitude":-0.000075,"longitude":-51.10248333333334,"time":1587188832000},
   {"latitude": -0.000075,"longitude":-51.10248333333334,"time":1587189098000}
]
```
