### ISSUE TITLE
Time slaiders and Save button are greyed out in the Publisher.

### ISSUE THREAD

**Issue by E3V3A** [tripleblindmarket/safe-places#46]
Both the *time-sliders* and the *Publish* button are grayed out in the apps.
What's going on? 

![firefox_2020-04-12_23-14-17](https://user-images.githubusercontent.com/194392/79078848-e949cd00-7d13-11ea-8f89-d149d300ef96.png)

**Comment by penrods** [comment]
They are grayed until you load data.+
