### ISSUE TITLE
Time range is not accurate in the UI

### ISSUE THREAD

**Issue by AdamLeonSmith** [tripleblindmarket/safe-places#53]
The time range is not accurate in the UI.  I uploaded a small dataset covering a couple of hours in the redaction tool, and the range was displayed as "18/04/2020, 00:00:00—19/04/2020, 01:00:00".  The actual time window is much smaller.

Steps to reproduce

1.  Unzip and upload the attached file into the redaction tool
2.  Look at the date/time range slider labels.
[1587215334455.zip](https://github.com/tripleblindmarket/safe-places/files/4496685/1587215334455.zip)

**Comment by mundanelunacy** [comment]
Should be addressed in dev_mvp_timezone

**Comment by mundanelunacy** [comment]
addressed in https://github.com/Path-Check/safeplaces-frontend/issues/9
