### ISSUE TITLE
A JS error popup appears when a redacted file is loaded into the publishing tool

### ISSUE THREAD

**Issue by AdamLeonSmith** [tripleblindmarket/safe-places#58]
**Steps to reproduce:**

1.  Redact a file and export from the redaction tool
2.  Load the file into the publishing tool

**Expected Behaviour**
File is loaded with no errors

**Actual Behaviour**
The file is loaded, but a popup appears that says "[object file]".  The below stack trace is visible in the console:

jquery.min.js:2 Uncaught TypeError: Cannot read property 'length' of undefined
    at updateStats (index.html:1504)
    at updateExposurePoints (index.html:1404)
    at updateDateRange (index.html:1343)
    at HTMLDocument.<anonymous> (index.html:1314)
    at e (jquery.min.js:2)
    at t (jquery.min.js:2)

**Comment by penrods** [comment]
@kylemtowle I believe this is correct in the Develop branch.  Do you want to validate it and merge Develop into Master?

**Comment by adityatr** [comment]
I don't get the message now, is it possible for you to upload the file which gives you the error

**Comment by AdamLeonSmith** [comment]
I retested on develop and I no longer get the error.  Closing, thanks.
