### ISSUE TITLE
Delete All button is highlighted instead of Delete button

### ISSUE THREAD

**Issue by meekg33k** [tripleblindmarket/safe-places#63]
## Current Behavior
When I select a point to delete on the Redaction tool, the **Delete All** button is highlighted, instead of the **Delete button**

![Screenshot (56)](https://user-images.githubusercontent.com/14355147/79770060-c1450580-82e1-11ea-8f51-9f7de5fa7497.png)

## Expected Behavior
The **Delete** button should be highlighted

**Comment by colezemel** [comment]
Are you sure there is only one point selected? I had this problem before but when I zoomed in I realized there was actually a bunch of points in the selected area. If this is the case maybe we should add something that tells the user how many points are selected?

**Comment by mundanelunacy** [comment]
@meekg33k @colezemel 

addressed in new repo https://github.com/Path-Check/safeplaces-frontend/issues/2
